apiVersion: v1
kind: PersistentVolume
metadata:
  name: tom-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shared/tom
    server: 211.183.3.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tom-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
