apiVersion: v1
kind: ConfigMap
metadata:
  name: tom-configmap
  namespace: default
data:
  index.jsp: |
    <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    <%@ page import="java.sql.*"%>
    <h1>DB</h2>
    <%
            Connection conn=null;
            try{
                    String Url="jdbc:mysql://db-svc/tomdb";
                    String Id="tomuser";
                    String Pass="test123";

                    Class.forName("com.mysql.jdbc.Driver");
                    conn=DriverManager.getConnection(Url,Id,Pass);
                    out.println("was-db Connection Success!");
            }catch(Exception e) {
                    e.printStackTrace(); 
    }
    %> 
